CREATE DATABASE IF NOT EXISTS etl_visitas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE etl_visitas;

CREATE TABLE etl_ejecucion (id_ejecucion BIGINT AUTO_INCREMENT PRIMARY KEY, fecha_negocio DATE NOT NULL, fecha_inicio DATETIME NOT NULL, fecha_fin DATETIME NULL, estatus ENUM('EN_CURSO','OK','OK_CON_ADVERTENCIAS','FALLIDO') NOT NULL DEFAULT 'EN_CURSO', archivos_detectados INT NOT NULL DEFAULT 0, archivos_cargados INT NOT NULL DEFAULT 0, archivos_omitidos INT NOT NULL DEFAULT 0, archivos_rechazados INT NOT NULL DEFAULT 0, registros_leidos INT NOT NULL DEFAULT 0, registros_cargados INT NOT NULL DEFAULT 0, registros_error INT NOT NULL DEFAULT 0, registros_advertencia INT NOT NULL DEFAULT 0, duracion_segundos INT NULL, host_ejecucion VARCHAR(100) NULL, mensaje VARCHAR(500) NULL, INDEX idx_fecha (fecha_negocio)) ENGINE=InnoDB;
CREATE TABLE etl_archivo (id_archivo BIGINT AUTO_INCREMENT PRIMARY KEY, id_ejecucion BIGINT NOT NULL, nombre_archivo VARCHAR(255) NOT NULL, hash_archivo CHAR(64) NOT NULL, bytes BIGINT NOT NULL, fecha_modif_origen DATETIME NULL, fecha_deteccion DATETIME NOT NULL, fecha_carga DATETIME NULL, estatus ENUM('DESCARGADO','VALIDADO','CARGADO','RECHAZADO','RESPALDADO','PURGADO_ORIGEN') NOT NULL DEFAULT 'DESCARGADO', registros_leidos INT NOT NULL DEFAULT 0, registros_validos INT NOT NULL DEFAULT 0, registros_error INT NOT NULL DEFAULT 0, motivo_rechazo VARCHAR(500) NULL, archivo_zip VARCHAR(255) NULL, UNIQUE KEY uk_hash (hash_archivo), INDEX idx_nombre (nombre_archivo), CONSTRAINT fk_arch_ejec FOREIGN KEY (id_ejecucion) REFERENCES etl_ejecucion(id_ejecucion)) ENGINE=InnoDB;
CREATE TABLE stg_visitas (id_stg BIGINT AUTO_INCREMENT PRIMARY KEY, id_archivo BIGINT NOT NULL, num_linea INT NOT NULL, email VARCHAR(320), jyv VARCHAR(50), badmail VARCHAR(50), baja VARCHAR(50), fecha_envio VARCHAR(50), fecha_open VARCHAR(50), opens VARCHAR(20), opens_virales VARCHAR(20), fecha_click VARCHAR(50), clicks VARCHAR(20), clicks_virales VARCHAR(20), links VARCHAR(255), ips VARCHAR(500), navegadores VARCHAR(255), plataformas VARCHAR(255), INDEX idx_archivo (id_archivo)) ENGINE=InnoDB;
CREATE TABLE visita (email VARCHAR(320) NOT NULL, fecha_visita DATETIME NOT NULL, clicks INT NOT NULL DEFAULT 1, id_archivo BIGINT NOT NULL, fecha_carga DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (email, fecha_visita), INDEX idx_fecha (fecha_visita)) ENGINE=InnoDB;
CREATE TABLE visitante (email VARCHAR(320) NOT NULL PRIMARY KEY, fechaPrimeraVisita DATE NOT NULL, fechaUltimaVisita DATE NOT NULL, visitasTotales INT NOT NULL DEFAULT 0, visitasAnioActual INT NOT NULL DEFAULT 0, visitasMesActual INT NOT NULL DEFAULT 0, fecha_actualizacion DATETIME NOT NULL) ENGINE=InnoDB;
CREATE TABLE estadistica (id_estadistica BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(320) NOT NULL, jyv VARCHAR(50) NULL, badmail VARCHAR(50) NULL, baja VARCHAR(50) NULL, fecha_envio DATETIME NOT NULL, fecha_open DATETIME NULL, opens INT NOT NULL DEFAULT 0, opens_virales INT NOT NULL DEFAULT 0, fecha_click DATETIME NULL, clicks INT NOT NULL DEFAULT 0, clicks_virales INT NOT NULL DEFAULT 0, links VARCHAR(255) NULL, ips VARCHAR(500) NULL, navegadores VARCHAR(255) NULL, plataformas VARCHAR(255) NULL, id_archivo BIGINT NOT NULL, fecha_carga DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_natural (email, fecha_envio), INDEX idx_fecha_envio (fecha_envio)) ENGINE=InnoDB;
CREATE TABLE errores (id_error BIGINT AUTO_INCREMENT PRIMARY KEY, id_ejecucion BIGINT NOT NULL, id_archivo BIGINT NULL, nombre_archivo VARCHAR(255) NULL, num_linea INT NULL, codigo_error VARCHAR(20) NOT NULL, severidad ENUM('RECHAZO','ADVERTENCIA') NOT NULL, campo VARCHAR(50) NULL, valor_original VARCHAR(500) NULL, descripcion VARCHAR(255) NOT NULL, registro_completo TEXT NULL, fecha_deteccion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_ejecucion (id_ejecucion), INDEX idx_codigo (codigo_error)) ENGINE=InnoDB;
CREATE TABLE cat_validacion (codigo_error VARCHAR(20) NOT NULL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, descripcion VARCHAR(300) NOT NULL, severidad ENUM('RECHAZO','ADVERTENCIA') NOT NULL, nivel ENUM('ARCHIVO','REGISTRO') NOT NULL, accion_operacion VARCHAR(300) NOT NULL) ENGINE=InnoDB;

INSERT INTO cat_validacion VALUES ('V-01','Layout: número de columnas','El archivo no tiene 15 columnas','RECHAZO','ARCHIVO', 'No se carga ni se borra del origen. Escalar a Desarrollo.'), ('V-02','Layout: nombre de encabezado','Un encabezado no coincide pero la estructura sí','ADVERTENCIA','ARCHIVO', 'El archivo se carga. Reportar al proveedor del origen.'), ('V-03','Email inválido','El campo email no cumple el patrón','RECHAZO','REGISTRO', 'A tabla errores. Si supera 5% del archivo, escalar.'), ('V-04','Fecha envío inválida','Nula o fuera de dd/mm/yyyy HH:mm','RECHAZO','REGISTRO', 'A tabla errores. Sin ella no hay hecho que fechar.'), ('V-05','Fecha secundaria inválida','Fecha open o click fuera de formato','ADVERTENCIA','REGISTRO', 'Se carga con la fecha en NULL. Monitorear tendencia.'), ('V-06','Campo numérico inválido','Opens o Clicks no numéricos','ADVERTENCIA','REGISTRO', 'Se carga con valor 0. Monitorear tendencia.'), ('V-07','Duplicado en lote','Mismo email y fecha envío repetido','ADVERTENCIA','REGISTRO', 'Se conserva el más completo. El descartado queda en errores.'), ('V-08','Coherencia temporal','Apertura o click anterior al envío','ADVERTENCIA','REGISTRO', 'Se carga. Si se dispara, probable desfase de zona horaria en origen.'), ('V-09','Columna vacía al 100%','Una columna esperada vino totalmente nula','ADVERTENCIA','ARCHIVO', 'Notificar. Puede ser que el origen dejó de enviar el campo.'), ('V-10','Coherencia de embudo','Hay clicks pero no hay fecha de apertura','ADVERTENCIA','REGISTRO', 'Se carga. Indica pérdida del evento intermedio en el origen.');
