services:
  mysql:
    image: mysql:8.0
    container_name: etl_visitas_mysql
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl_visitas
      MYSQL_USER: etl
      MYSQL_PASSWORD: etl
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
